https://pypi.org/project/questrade-api/

In [4]:
import sys
import os
#from questrade_api import Questrade
from questrade_api.questrade import Questrade
import pandas as pd
#import datetime
from datetime import datetime, timedelta
from pytz import timezone

#sys.path.append(..)

token : 3QE89heh6KSagWLX_BOOBkQJbre98--c0
2nd token  _vazKu-uXvRXa_j1nGP7Tp_7Aa3agNNQ0
investinu eaPvXL4pAbBp3YEKZc7at6jN_LmXV15o0

In [7]:
# INTIALLY SET TOKEN

token = input('Refresh Token: ')
q = Questrade(refresh_token=token)
print('token :',token)
print(q)

Refresh Token:  iH6CKXIGmCgm-jy4wuEBA12cHbT2_mDW0

token : iH6CKXIGmCgm-jy4wuEBA12cHbT2_mDW0
<questrade_api.questrade.Questrade object at 0x000002CE8C875970>

In [2]:
# AFTER TOKEN HAS BEEN REGISTER USE THIS

q = Questrade()
print(q)

<questrade_api.questrade.Questrade object at 0x00000295853F55B0>

In [20]:
# TIME
def server_time():
    st=q.time
    server_time = st.get('time')
    return server_time

def time_name():
    timename = server_time().replace(':','-')
    return timename

def start_date(days_back):
    date_part = server_time()[:10]
    rest_of_it = server_time()[10:]
    date_format = "%Y-%m-%d"
    date_object = datetime.strptime(date_part, date_format)
    tdelta = timedelta(days=days_back)
    last_month_date_obj = date_object - tdelta
    last_month = last_month_date_obj.strftime(date_format)
    start_date = last_month + rest_of_it
    return(start_date)
    
    
print(server_time())
print(time_name())
start_date(30)
print(start_date(30))

2021-08-11T00:18:51.781000-04:00
2021-08-11T00-18-52.170000-04-00
2021-07-12T00:18:54.671000-04:00

In [28]:
# Set file foler path for exports
filefolder = 'D:\Dropbox\- INVESTINU\- QUESTRADE_API EXPORTS\ACCOUNT 1'
#filefolder = 'D:\Dropbox\- INVESTINU\- QUESTRADE_API EXPORTS\ACCOUNT 2'
print('using :', filefolder)

using : D:\Dropbox\- INVESTINU\- QUESTRADE_API EXPORTS\ACCOUNT 1

In [25]:
# ACCOUNTS
def accounts():
    filename = os.path.join(filefolder, 'accounts.xlsx')
    dict_accounts = q.accounts
    dict_accounts
    user_id = q.accounts['userId']
    print('user_id :',user_id)
    df_accounts = pd.DataFrame.from_dict(q.accounts['accounts']) #de-nest the accounts dict and make df
    display(df_accounts)
    df_accounts.to_excel(filename, header=True, )
    return('success')

accounts()

user_id : 1292261

     type    number  status  isPrimary  isBilling clientAccountType
0  Margin  28063756  Active      False      False        Individual
1  Margin  28148589  Active      False      False       Corporation
2    TFSA  52473463  Active      False      False        Individual
3    RRSP  52490693  Active      False      False        Individual

'success'

In [26]:
# GET ACCOUNT ID

id = input('Enter Account ID :')
#id = '28231880'
print('Using Account: ',id)

Enter Account ID : 28148589

Using Account:  28148589

In [31]:
# ACCOUNT POSITIONS
def account_positions():
    filename = os.path.join(filefolder, id+'-positions-'+time_name()+'.xlsx')
    dict_positions = q.account_positions(id)
    #print(dict_positions)
    position_list = dict_positions['positions']
    df_positions = pd.DataFrame.from_dict(position_list)
    display(df_positions)
    df_positions.to_excel(filename, header=True, )
    return('success')

account_positions()

,symbol,symbolId,openQuantity,closedQuantity,currentMarketValue,currentPrice,averageEntryPrice,dayPnl,closedPnl,openPnl,totalCost,isRealTime,isUnderReorg
0,INPX,28504832,10000,0,10400.00,1.04000,1.079000,-100.00,0.0000,-390.00000,10790.00000,False,False
1,MT.VN,26639880,20000,0,2700.00,0.13500,0.122075,100.00,0.0000,258.50000,2441.50000,False,False
2,LQDA,22400523,400,0,964.00,2.41000,3.003000,12.00,0.0000,-237.20000,1201.20000,False,False
3,TBLT,30099980,6000,0,3940.20,0.65670,0.690000,14.40,0.0000,-199.80000,4140.00000,False,False
4,ABIO,25311505,2500,0,7650.00,3.06000,3.550000,0.00,0.0000,-1225.00000,8875.00000,False,False
5,NAT,44317,1000,0,2360.00,2.36000,3.540000,60.00,0.0000,-1180.00000,3540.00000,False,False
6,PBLA,33337897,2000,0,4900.00,2.45000,4.246970,20.00,0.0000,-3593.94000,8493.94000,False,False
7,ASTSW,35424817,100,100,350.00,3.50000,2.655000,-12.00,264.5000,84.50000,265.50000,False,False
8,NICL.VN,33002807,30000,0,2400.00,0.08000,0.125000,0.00,0.0000,-1350.00000,3750.00000,False,False
9,FLMNW,22771775,3000,0,300.00,0.10000,0.180000,0.30,0.0000,-240.00000,540.00000,False,False
10,NIKLF,33002818,10000,0,659.60,0.06596,0.094820,14.60,0.0000,-288.60000,948.20000,False,False
11,SKYG.VN,28114754,5000,0,525.00,0.10500,0.220000,-25.00,0.0000,-575.00000,1100.00000,False,False
12,CLVRW,33647952,350,0,745.50,2.13000,1.590000,3.50,0.0000,189.00000,556.50000,False,False
13,CLVR,33647953,700,300,7700.00,11.00000,8.400000,21.00,1080.0000,1820.00000,5880.00000,False,False
14,LUMO,29650010,200,0,1486.00,7.43000,11.200000,-32.00,0.0000,-754.00000,2240.00000,False,False
15,BKYI,33213026,1000,0,3360.00,3.36000,3.570000,50.00,0.0000,-210.00000,3570.00000,False,False
16,QSI,36486253,1000,0,8830.00,8.83000,9.750000,-280.00,0.0000,-920.00000,9750.00000,False,False
17,ASTC,19148407,2000,0,2260.00,1.13000,1.228400,100.00,0.0000,-196.80000,2456.80000,False,False
18,BITK.VN,21751426,8000,0,4400.00,0.55000,0.550000,-80.00,0.0000,0.00000,4400.00000,False,False
19,TPST,36787844,53,0,723.45,13.65000,13.360000,-55.65,0.0000,15.37000,708.08000,False,False
20,IMR.VN,32080019,10000,0,900.00,0.09000,0.100000,-50.00,0.0000,-100.00000,1000.00000,False,False
21,HUT.TO,20782742,800,0,6304.00,7.88000,5.260000,-144.00,0.0000,2096.00000,4208.00000,False,False
22,GOEVW,33688474,300,300,599.97,1.99990,1.836667,14.94,540.9999,48.96990,551.00010,False,False
23,GOEV,33688475,600,0,4794.00,7.99000,7.998900,6.00,0.0000,-5.34000,4799.34000,False,False
24,YVR,23327645,5000,0,9600.00,1.92000,1.880000,-100.00,0.0000,200.00000,9400.00000,False,False
25,DFFN,24041638,9000,0,5121.90,0.56910,0.790000,214.20,0.0000,-1988.10000,7110.00000,False,False
26,TBLTW,23932327,5000,0,1027.00,0.20540,0.200000,-72.50,0.0000,27.00000,1000.00000,False,False
27,IMCC.CN,34514093,1440,0,9014.40,6.26000,5.146667,86.40,0.0000,1603.19952,7411.20048,False,False
28,AGL.VN,17605807,15000,0,3225.00,0.21500,0.300000,-525.00,0.0000,-1275.00000,4500.00000,False,False
29,NUMI.VN,30630074,8000,0,7440.00,0.93000,0.999375,-160.00,0.0000,-555.00000,7995.00000,False,False
30,DML.TO,15815,3000,0,4170.00,1.39000,1.530000,270.00,0.0000,-420.00000,4590.00000,False,False
31,WKG.VN,28117979,20000,0,3000.00,0.15000,0.170000,0.00,0.0000,-400.00000,3400.00000,False,False
32,MDX.VN,27105,14000,0,1680.00,0.12000,0.149857,0.00,0.0000,-417.99800,2097.99800,False,False
33,DSS,30459108,1000,0,1310.00,1.31000,2.850000,-40.00,0.0000,-1540.00000,2850.00000,False,False

'success'

In [30]:
# ACCOUNT BALANCES - COMBINED

def account_balances():
    filename = os.path.join(filefolder, id+'-balances-'+time_name()+'.xlsx')
    dict_balances = q.account_balances(id)
    #combined_balances1 = dict_balances['perCurrencyBalances']
    #combined_balances2 = dict_balances['combinedBalances']
    #combined_balances3 = dict_balances['sodPerCurrencyBalances']
    #combined_balances4 = dict_balances['sodCombinedBalances']
    df_combined_balances1 = pd.DataFrame.from_dict(dict_balances['perCurrencyBalances'])  #Per balances: True CAD and USD native amounts
    df_combined_balances2 = pd.DataFrame.from_dict(dict_balances['combinedBalances'])  #combined : each row is TOTAL value in that currency - could be used for the 3rd row : combined in CAD
    df_combined_balances3 = pd.DataFrame.from_dict(dict_balances['sodPerCurrencyBalances'])# sod per Currency balances : The MOST ACCURATE to what is shown in account.
    df_combined_balances4= pd.DataFrame.from_dict(dict_balances['sodCombinedBalances'])# sod combined balances : Combined totals of sod per currency for use in 3rd row
    #display(df_combined_balances1)
    #display(df_combined_balances2)
    display(df_combined_balances3)
    display(df_combined_balances4)
    df_combined_balances3.to_excel(r'D:\Dropbox\- INVESTINU\- QUESTRADE_API EXPORTS\ACCOUNT 2\combined_currency_balances.xlsx', header=True, )
    df_combined_balances4.to_excel(r'D:\Dropbox\- INVESTINU\- QUESTRADE_API EXPORTS\ACCOUNT 2\combined_total_balances.xlsx', header=True, )
    df_combined_balances3.to_excel(filename, header=True)
    df_combined_balances4.to_excel(filename, header=True)
    return('success')

account_balances()

,currency,cash,marketValue,totalEquity,buyingPower,maintenanceExcess,isRealTime
0,CAD,7668.250000,45283.4,52951.650000,30734.23500,9229.500000,True
1,USD,14752.270006,79226.1,93978.370006,98644.82312,29623.070006,True

,currency,cash,marketValue,totalEquity,buyingPower,maintenanceExcess,isRealTime
0,CAD,26224.392827,144937.949885,171162.342712,152084.250415,45670.94607,True
1,USD,20848.585147,115226.736006,136075.321153,122541.099735,36799.12905,True

'success'

In [32]:
# ORDERS
def orders(start_time):
    filename = os.path.join(filefolder, id+'-orders-'+time_name()+'.xlsx')
    dict_orders = q.account_orders(id, startTime=start_time)
    df_orders = pd.DataFrame.from_dict(dict_orders['orders'])
    #display(df_orders)
    df_orders.to_excel(filename, header=True)
    return('success')

orders('2021-01-01T00:00:00-0')

'success'

In [40]:
# INDIVIDUAL ORDER DETAIL
dict_order = q.account_order(id, 906251374)
dict_order['orders']
df_order = pd.DataFrame.from_dict(dict_order['orders'])
display(df_order)

Empty DataFrame
Columns: []
Index: []

In [33]:
# EXECUTIONS
def executions(start_time):
    filename = os.path.join(filefolder, id+'-executions-'+time_name()+'.xlsx')
    #print(filepath)
    dict_executions = q.account_executions(id, startTime=start_time)
    #dict_executions
    df_executions = pd.DataFrame.from_dict(dict_executions['executions'])
    display(df_executions)
    df_executions.to_excel(filename, header=True, )
    return('success')

executions('2021-01-01T00:00:00-0')

,symbol,symbolId,quantity,side,price,id,orderId,orderChainId,exchangeExecId,timestamp,notes,venue,totalCost,orderPlacementCommission,commission,executionFee,secFee,legId,canadianExecutionFee,parentId
0,BYSI,16887775,1000,Sell,9.0029,1143201941,908964115,876165798,231896325,2021-07-27T13:56:21.000000-04:00,,CTDLBN,9002.9,0,9.95,0.0,0.045915,0,0,1143201941
1,NSPR,35790135,1000,Sell,4.0162,1141110026,907948920,875132200,206000138,2021-07-26T09:50:24.000000-04:00,,CTDLBN,4016.2,0,9.95,0.0,0.020483,0,0,1141110026
2,WKG.VN,28117979,2500,Buy,0.2100,1138606592,906609002,906609002,S3-19654,2021-07-22T10:51:05.000000-04:00,,TSXV,525.0,0,0.00,0.0,0.000000,0,0,1138606592
3,AGL.VN,17605807,15000,Buy,0.3000,1138502585,906612944,906612944,S3-15857,2021-07-22T10:21:17.000000-04:00,,TSXV,4500.0,0,9.95,12.0,0.000000,0,0,1138502585
4,WKG.VN,28117979,2500,Buy,0.2100,1138494642,906609002,906609002,S3-15523,2021-07-22T10:18:21.000000-04:00,,OME,525.0,0,9.95,2.0,0.000000,0,0,1138494642
5,WKG.VN,28117979,2500,Buy,0.2100,1138494644,906609002,906609002,S3-15524,2021-07-22T10:18:21.000000-04:00,,CX2,525.0,0,0.00,2.0,0.000000,0,0,1138494644
6,WKG.VN,28117979,500,Buy,0.2100,1138494646,906609002,906609002,S3-15525,2021-07-22T10:18:21.000000-04:00,,AQN,105.0,0,0.00,0.4,0.000000,0,0,1138494646
7,WKG.VN,28117979,2000,Buy,0.2100,1138494648,906609002,906609002,S3-15526,2021-07-22T10:18:21.000000-04:00,,TSXV,420.0,0,0.00,1.6,0.000000,0,0,1138494648
8,HUT.TO,20782742,100,Buy,5.2600,1137821947,906251374,906251374,S3-43995,2021-07-21T14:32:20.000000-04:00,,TSX,526.0,0,4.95,0.0,0.000000,0,0,1137821947
9,HUT.TO,20782742,500,Buy,5.2600,1137821949,906251374,906251374,S3-43996,2021-07-21T14:32:20.000000-04:00,,TSX,2630.0,0,1.05,0.0,0.000000,0,0,1137821949
10,HUT.TO,20782742,200,Buy,5.2600,1137821951,906251374,906251374,S3-43997,2021-07-21T14:32:20.000000-04:00,,TSX,1052.0,0,2.00,0.0,0.000000,0,0,1137821951
11,DEFI.TO,34856813,1500,Sell,0.6800,1131769945,903240360,875994670,S3-47505,2021-07-15T13:48:14.000000-04:00,,AQL,1020.0,0,0.00,0.0,0.000000,0,0,1131769945
12,DEFI.TO,34856813,3000,Sell,0.6800,1131769941,903240360,875994670,S3-47503,2021-07-15T13:48:14.000000-04:00,,AQL,2040.0,0,0.00,0.0,0.000000,0,0,1131769941
13,DEFI.TO,34856813,1500,Sell,0.7000,1131769933,903240360,875994670,S3-47499,2021-07-15T13:48:14.000000-04:00,,AQL,1050.0,0,9.95,1.2,0.000000,0,0,1131769933
14,DEFI.TO,34856813,1000,Sell,0.7000,1131769935,903240360,875994670,S3-47500,2021-07-15T13:48:14.000000-04:00,,AQL,700.0,0,0.00,0.8,0.000000,0,0,1131769935
15,DEFI.TO,34856813,500,Sell,0.7000,1131769937,903240360,875994670,S3-47501,2021-07-15T13:48:14.000000-04:00,,AQL,350.0,0,0.00,0.4,0.000000,0,0,1131769937
16,DEFI.TO,34856813,500,Sell,0.6800,1131769939,903240360,875994670,S3-47502,2021-07-15T13:48:14.000000-04:00,,AQL,340.0,0,0.00,0.4,0.000000,0,0,1131769939
17,WEED.TO,16529510,400,Sell,26.0000,1130403296,902576210,873497653,S3-51115,2021-07-14T14:28:18.000000-04:00,,ALPH,10400.0,0,4.95,1.4,0.000000,0,0,1130403296
18,HEXO.TO,33701175,1000,Sell,6.1000,1126570163,900723524,874644477,S3-14305,2021-07-12T09:45:49.000000-04:00,,ALPH,6100.0,0,9.95,3.5,0.000000,0,0,1126570163

'success'

In [35]:
# ACCOUNT ACTIVITIES --- only 30 days
def activities():
    filename = os.path.join(filefolder, id+'-activities-'+time_name()+'.xlsx')
    dict_activities = q.account_activities(id, startTime=start_date(30))
    #print(dict_activities)
    df_activities = pd.DataFrame.from_dict(dict_activities['activities'])
    display(df_activities)
    df_activities.to_excel(filename, header=True, )
    return('success')

activities()

,tradeDate,transactionDate,settlementDate,action,symbol,symbolId,description,currency,quantity,price,grossAmount,commission,netAmount,type
0,2021-07-12T00:00:00.000000-04:00,2021-07-14T00:00:00.000000-04:00,2021-07-14T00:00:00.000000-04:00,Sell,HEXO.TO,33701175,HEXO CORP COM NEW WE ACTED AS AGENT,CAD,-1000,6.1000,6100.0,-13.45,6086.55,Trades
1,2021-07-14T00:00:00.000000-04:00,2021-07-16T00:00:00.000000-04:00,2021-07-16T00:00:00.000000-04:00,Sell,WEED.TO,16529510,CANOPY GROWTH CORPORATION COMMON SHARES WE A...,CAD,-400,26.0000,10400.0,-6.35,10393.65,Trades
2,2021-07-15T00:00:00.000000-04:00,2021-07-19T00:00:00.000000-04:00,2021-07-19T00:00:00.000000-04:00,Sell,DEFI.TO,34856813,DEFI TECHNOLOGIES INC COM WE ACTED AS AGENT ...,CAD,-8000,0.6875,5500.0,-12.75,5487.25,Trades
3,2021-07-21T00:00:00.000000-04:00,2021-07-23T00:00:00.000000-04:00,2021-07-23T00:00:00.000000-04:00,Buy,HUT.TO,20782742,HUT 8 MINING CORP NEW COMMON WE ACTED AS AGE...,CAD,800,5.2600,-4208.0,-8.00,-4216.00,Trades
4,2021-07-22T00:00:00.000000-04:00,2021-07-26T00:00:00.000000-04:00,2021-07-26T00:00:00.000000-04:00,Buy,AGL.VN,17605807,AGUILA AMERN GOLD LTD COM NO PAR WE ACTED AS...,CAD,15000,0.3000,-4500.0,-21.95,-4521.95,Trades
5,2021-07-22T00:00:00.000000-04:00,2021-07-26T00:00:00.000000-04:00,2021-07-26T00:00:00.000000-04:00,Buy,WKG.VN,28117979,WESTKAM GOLD CORP COM NEW WE ACTED AS AGENT,CAD,2500,0.2100,-525.0,-2.00,-527.00,Trades
6,2021-07-22T00:00:00.000000-04:00,2021-07-26T00:00:00.000000-04:00,2021-07-26T00:00:00.000000-04:00,Buy,WKG.VN,28117979,WESTKAM GOLD CORP COM NEW WE ACTED AS AGENT,CAD,2500,0.2100,-525.0,-11.95,-536.95,Trades
7,2021-07-22T00:00:00.000000-04:00,2021-07-26T00:00:00.000000-04:00,2021-07-26T00:00:00.000000-04:00,Buy,WKG.VN,28117979,WESTKAM GOLD CORP COM NEW WE ACTED AS AGENT,CAD,500,0.2100,-105.0,-0.40,-105.40,Trades
8,2021-07-22T00:00:00.000000-04:00,2021-07-26T00:00:00.000000-04:00,2021-07-26T00:00:00.000000-04:00,Buy,WKG.VN,28117979,WESTKAM GOLD CORP COM NEW WE ACTED AS AGENT ...,CAD,4500,0.2100,-945.0,-1.60,-946.60,Trades
9,2021-07-26T00:00:00.000000-04:00,2021-07-28T00:00:00.000000-04:00,2021-07-28T00:00:00.000000-04:00,Sell,NSPR,35790135,INSPIREMD INC COMMON STOCK WE ACTED AS AGENT,USD,-1000,4.0162,4016.2,-9.98,4006.22,Trades
10,2021-07-27T00:00:00.000000-04:00,2021-07-29T00:00:00.000000-04:00,2021-07-29T00:00:00.000000-04:00,Sell,BYSI,16887775,BEYONDSPRING INC ORDINARY SHARES WE ACTED AS...,USD,-1000,9.0029,9002.9,-10.00,8992.90,Trades
11,2021-07-14T00:00:00.000000-04:00,2021-07-14T00:00:00.000000-04:00,2021-07-14T00:00:00.000000-04:00,MGR,IMCC.CN,34514093,IM CANNABIS CORP COM NEW SHRS RECEIVED THRU ME...,CAD,440,0.0000,0.0,0.00,0.00,Corporate actions
12,2021-07-14T00:00:00.000000-04:00,2021-07-14T00:00:00.000000-04:00,2021-07-14T00:00:00.000000-04:00,MGR,MYM.CN,13022458,MYM NUTRACEUTICALS INC COM PLAN OF ARRANGEMENT...,CAD,-20000,0.0000,0.0,0.00,0.00,Corporate actions
13,2021-07-20T00:00:00.000000-04:00,2021-07-20T00:00:00.000000-04:00,2021-07-20T00:00:00.000000-04:00,FXT,,0,CONVERSION - CAD/USD,CAD,0,0.0000,0.0,0.00,-128820.00,FX conversion
14,2021-07-20T00:00:00.000000-04:00,2021-07-20T00:00:00.000000-04:00,2021-07-20T00:00:00.000000-04:00,FXT,,0,CONVERSION - CAD/USD,USD,0,0.0000,0.0,0.00,100000.00,FX conversion
15,2021-07-16T00:00:00.000000-04:00,2021-07-16T00:00:00.000000-04:00,2021-07-16T00:00:00.000000-04:00,,,0,"INT FR 06/16 THRU07/15@ 6 % BAL 97,718 ...",USD,0,0.0000,0.0,0.00,-528.04,Interest

'success'

In [17]:
# SYMBOL - uses symbole idonly

dict_symbol = q.symbol(34231109)
dict_symbol
df_symbol = pd.DataFrame.from_dict(dict_symbol['symbols'])
display(df_symbol)

,symbol,symbolId,prevDayClosePrice,highPrice52,lowPrice52,averageVol3Months,averageVol20Days,outstandingShares,eps,pe,...,dividendDate,optionStrikePrice,isTradable,isQuotable,hasOptions,currency,minTicks,industrySector,industryGroup,industrySubgroup
0,XELA,34231109,3.22,7.82,0.9903,65663583,103516254,59192000,-11.51,None,...,2021-01-26T00:00:00.000000-05:00,None,True,True,True,USD,"[{'pivot': 0, 'minTick': 0.0001}, {'pivot': 1,...",Technology,Undefined,Undefined

In [18]:
# SYMBOLs - can use symbols or id

dict_symbols = q.symbols(ids='34231109,34856813')
dict_symbols
df_symbols = pd.DataFrame.from_dict(dict_symbols['symbols'])
display(df_symbols)

,symbol,symbolId,prevDayClosePrice,highPrice52,lowPrice52,averageVol3Months,averageVol20Days,outstandingShares,eps,pe,...,dividendDate,optionStrikePrice,isTradable,isQuotable,hasOptions,currency,minTicks,industrySector,industryGroup,industrySubgroup
0,XELA,34231109,3.22,7.82,0.9903,65663583,103516254,59192000.0,-11.51,None,...,2021-01-26T00:00:00.000000-05:00,None,True,True,True,USD,"[{'pivot': 0, 'minTick': 0.0001}, {'pivot': 1,...",Technology,Undefined,Undefined
1,DEFI.TO,34856813,1.14,NaN,NaN,524421,631095,NaN,NaN,None,...,None,None,True,True,False,CAD,"[{'pivot': 0, 'minTick': 0.005}, {'pivot': 0.5...",FinancialServices,Undefined,Undefined